# Site Settings
title: Anish Resume
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Anish Grandhi
tagline: Data Scientist
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Being curious, solving challenges and demonstrating my work is I believe has led me to become a data scientist. 
I have interned as a data scientist for 7 months and the experience has bolstered my ambitions. 
Competencies - Data Science, Machine Learning, Big Data technologies, cloud computing, Hadoop, Spark, Python, R, 
Data visualization - Tableau, PowerBI, D3.js.'

#sidebar links
email: anish12392@gmail.com
phone: 682 433 1727
website: anishgrandhi.github.io/resume/ #do not add http://
linkedin: anishgrandhi
github: anishgrandhi
twitter: '@anishgrandhi'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
